apiVersion: v1
kind: Namespace
metadata:
  name: uhdre-gamdi-web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alb
  namespace: uhdre-gamdi-web    # 각자 서비스의 ns로 변경
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-svc-alb
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc-alb
  namespace: uhdre-gamdi-web    # 각자 서비스의 ns로 변경
  labels:
    app: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy-alb
  namespace: uhdre-gamdi-web    # 각자 서비스의 ns로 변경
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${TAG}
          ports:
            - containerPort: 80